/* NAVIGATION */
const nav_EcranPrincipal = getElementById("mainMenu")
const nav_EcranLogin = getElementById("loginScreen")
const nav_EcranCreation = getElementById("statblockCreation")
const nav_EcranGallerie = getElementById("statblockGallery")

const info_stats = <HTMLElement>getElementById("info-stats")
const info_damage = <HTMLElement>getElementById("info-dam")
const info_damage_avg = getInputById("info-dam-avg")
const info_damage_dice = getSelectById("info-dam-dice")
const info_damage_formula = getInputById("info-dam-formula")
const info_damage_range = getInputById("info-dam-range")
const info_damage_maxDices = getInputById("info-dam-maxDices")
const info_damage_maxStatic = getInputById("info-dam-maxStatic")
const info_damage_multiplier = getInputById("info-dam-multiplier")
const info_preview = <HTMLElement>getElementById("info-prev")

const input_importJson = <HTMLInputElement>document.getElementById("import-statblock")
const githubUsername = <HTMLInputElement>document.getElementById("githubUsername")
const githubRepo = <HTMLInputElement>document.getElementById("githubRepo")

/* SECTION ENTÊTE */
const input_name = getInputById("name")
const input_level = getInputById("level")
const input_rank = getSelectById("rank")
const input_role = getSelectById("role")
const input_type = getSelectById("type")
const input_keywords = getInputById("keywords")
const input_size = getSelectById("size")
const input_origin = getSelectById("origin")
const input_form = getSelectById("form")

/* SECTION CALCULS */
const input_ac = getInputById("ac")
const input_hp = getInputById("hp")
const input_init = getInputById("init")
const input_perception = getInputById("perception")
const input_stealth = getInputById("stealth")
const input_speed = getInputById("speed")
const input_atk = getInputById("atk")
const input_dcLow = getInputById("dc-low")
const input_dmg = getInputById("dmg")
const input_prof = getInputById("prof")
const input_cr = getInputById("cr")
const input_xp = getInputById("xp")

/* SECTION STATSAUTRES */
const input_movement = getInputById("movement")
const input_skills = getInputById("skills")
const input_threshold = getInputById("dthreshold")
const input_vulnerable = getInputById("vulnerable")
const input_resistant = getInputById("resistant")
const input_dImmune = getInputById("dimmune")
const input_cImmune = getInputById("cimmune")
const input_senses = getInputById("senses")
const input_languages = getInputById("languages")